apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - name: secure-container
    image: nginx
    securityContext:
      runAsUser: 1000           # Runs as non-root user
      runAsGroup: 2000          # Group permissions
      readOnlyRootFilesystem: true  # Cannot modify filesystem
      allowPrivilegeEscalation: false  # Cannot escalate privileges
      privileged: false         # Cannot access the host system
      capabilities:
        drop: ["ALL"]           # Removes all Linux capabilities
