apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    supplementalGroups: [4000]
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged:latest  # Image that runs as non-root user
    ports:
      - containerPort: 8080  # Changing to a non-privileged port
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
      - name: nginx-cache
        mountPath: /var/cache/nginx
      - name: nginx-log
        mountPath: /var/log/nginx
      - name: nginx-html
        mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-cache
      emptyDir: {}
    - name: nginx-log
      emptyDir: {}
    - name: nginx-html
      emptyDir: {}
