apiVersion: v1
kind: ServiceAccount
metadata:
  name: web1-prod-user
  namespace: web1-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web1-prod-admin
  namespace: web1-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: web1-prod-user
  namespace: web1-prod
