apiVersion: v1
kind: ServiceAccount
metadata:
  name: web1-prod-user
  namespace: web1-prod

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web1-prod-user-full-access
  namespace: web1-prod
rules:
  - apiGroups: ["", "extensions", "apps", "namespace"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web1-prod-user-view
  namespace: web1-prod
subjects:
  - kind: ServiceAccount
    name: web1-prod-user
    namespace: web1-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web1-prod-full-access
