apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-installer-config
  namespace: wazuh
data:
  install.sh: |
    #!/bin/bash
    #sudo apt-get update -y
    #sudo apt --fix-broken install
    #sudo apt install curl -y
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
    #echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
    #sudo apt-get update
    sudo WAZUH_MANAGER="172.16.2.139" apt-get install wazuh-agent
    sudo systemctl daemon-reload
    sudo systemctl enable wazuh-agent
    sudo systemctl start wazuh-agent
    #sudo sed -i "s/^deb/#deb/" /etc/apt/sources.list.d/wazuh.list
    #sudo apt-get update
