apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-website
spec:
  selector:
    matchLabels:
      app: html-website
  replicas: 1
  template:
    metadata:
      labels:
        app: html-website
    spec:
      containers:
      - name: site
        image: linuxgeekup/html-website:vtag1
        imagePullPolicy: Always
        ports:
        - containerPort: 80