---
apiVersion: v1 
kind: PersistentVolumeClaim       
metadata:                          
  name: mysql-pv-claim
  labels:
    type: mysql-app 
spec:                               
  storageClassName: standard       
  accessModes: 
  - ReadWriteOnce             
  resources:
    requests:
      storage: 250Mi 

