apiVersion: v1
kind: Service
metadata:
  name: rke2-ingress-nginx-controller
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: rke2-ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080  # You can change this to any available port in the 30000-32767 range
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443  # You can change this to any available port in the 30000-32767 range
  type: NodePort
