apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: dev
spec:
  selector:
    matchLabels:
      app: site
  replicas: 1
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: shawon10/nginx-static-site
        volumeMounts:                 
        - name: config1               
          mountPath: /config/adil   
          readOnly: true
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      volumes:                          
      - name: config1                  
        configMap:                   
          name: adilh-configmap
